#!/bin/sh
# Launch your nanoHUB tool.
# Remove the “-A” flag if you want users to execute the notebook manually.

# 1)  cadet_ff.ipynb  ← exact notebook filename in the repo
# 2)  cadet-ff        ← the tool alias you picked in the Tool Pipeline
# 3)  anaconda-6      ← keep unless you need a different nanoHUB environment

/usr/bin/invoke_app "$@" -C "start_jupyter -t cadetff -T @tool CADeT.ipynb" \
    -t cadetff \
    -u anaconda-6

